- hosts: all
  tasks:
  - name: show IP address
    ansible.builtin.debug:
      msg: >
       This host uses IP address {{ ansible_facts.default_ipv4.address }}
      
      # Alternative way:
      # This host uses IP address {{ ansible_facts['default_ipv4']['address'] }}  
      # This host uses this scheduler mode {{ ansible_facts['devices']['loop0']['scheduler_mode'] }}  

# this playbook gathers all IPV4 address of all hosts.
