-name: installing docker on servers
  hosts: web-server 
  tasks: 
    - name: installing docker --------------------
      apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: enable docker --------------------
      service: 
        name: docker 
        enabled: yes
        start: yes